# Theme Github link: https://github.com/argvchs/hexo-theme-particlex
# Developer: argvchs

# html lang
language: zh

# avatar image url
head_img: /img/å¤´åƒ.png
# å¤´åƒ 

# home page head info block
head_block_enable: true

# home page head background style ç½‘ç«™é¦–é¡µå¤´å›¾
home_background: /img/å£çº¸.png

# WARNING! vf_fonts (variable fonts) feature is EXPERIMENTAL
# MDN: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
# ä¸çŸ¥é“ä»€ä¹ˆä¸œè¥¿ï¼Œä¿æŒé»˜è®¤
vf_fonts_enable: false

# ParticleX theme icon is adopts the font awesome 6
# Link: https://fontawesome.com/search/

# main menu navigation ç½‘ç«™é¡¶éƒ¨å¯¼èˆªæ 
menu:
    ä¸»é¡µ:
        name: house
        theme: solid
        src: # You shouldn't add anything else here
    å…³äº:
        name: id-card
        theme: solid
        src: about
    æ¡£æ¡ˆ:
        name: box-archive
        theme: solid
        src: archives
    åˆ†ç±»:
        name: bookmark
        theme: solid
        src: categories
    æ ‡ç­¾:
        name: tags
        theme: solid
        src: tags
    # Example:
    # <name>: # åå­—
    #     name: <icon-name> å›¾æ ‡åå­—ï¼Œåœ¨ https://fontawesome.com/search/ æ‰¾æœ‰æ²¡æœ‰è¦åŠ çš„
    #     theme: <icon-theme> æ— è„‘ç”¨ solid å¤§æ¦‚å°±è¡Œäº†
    #     src: <link-url> è·¯å¾„ï¼Œå‰é¢ä¸éœ€è¦åŠ  /

# side info card
card: #é¦–é¡µå³è¾¹æ¡†
    enable: true
    description: ["Description..."] # You can add more
    icon_links: # ç¤¾äº¤é“¾æ¥
        github:
            name: github
            theme: brands
            link: https://github.com/ShinoMoe
        twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/Shino_Moe_Main
        telegram:
            name: telegram
            theme: brands
            link: https://t.me/Shino_Moe
    friend_links: # å‹æƒ…é“¾æ¥
        æ‘‡æ›³çš„ç´«ä¸é¦™ğŸŒŒ: https://blog.lijiakaijun.cyou/
        Cynosura: https://blog.fonx.xyz/
        é±¼ç±»è§‚æµ‹ç ”ç©¶æ‰€: https://lz233.ac.cn/
        Moe23333's Blog: https://moe23333.vercel.app
        Isoheptane: https://blog.cascade.moe/
        # [] å‹æƒ…é“¾æ¥ä¸ºç©ºçš„æ—¶å€™æ‰ç”¨
        # Example:
        # <name>: <link-url> ç½‘ç«™åç§°: é“¾æ¥

# footer info ç½‘ç«™å°¾éƒ¨ï¼Œä¸€èˆ¬æˆ–è®¸ä¸éœ€è¦ä¿®æ”¹
footer:
    since: 20xx
    # Customize the server domain name ICP
    ICP:
        enable: true
        code: <a href="https://icp.gov.moe/?keyword=20228012" target="_blank">èŒICPå¤‡20228012å·</a>

# Gitalk è¯„è®ºï¼Œéœ€è¦æ¢å…¶ä»–çš„å°±è‡ªå·±æ”¹ï¼ˆç¡®ä¿¡ï¼‰
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.
    proxy: # CORS proxy
    sites: # Sites
        []
        # Example:
        # <www.example.com>:
        #    clientID: <client-id>
        #    clientSecret: <client-secret>