# ç½‘ç«™åŸºæœ¬é…ç½®
favicon: /img/å›¾æ ‡.jpg

# å¯é€‰ light | dark | auto | time
mode: auto


colors:
  primary: '#6200ee'
  # bg: "#F5F5F5" 
  # èƒŒæ™¯è‰²ï¼Œå¯é€‰
  selection_bg: '#8e71c1' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

# ç½‘ç«™å·¦ä¾§æ 
# ç¤¾äº¤é“¾æ¥
social:
  - name: GitHub
    link: https://github.com/YunYouJun
    icon: ri:github-line
    color: '#181717'
  - name: Twitter
    link: https://twitter.com/YunYouJun
    icon: ri:twitter-line
    color: '#1da1f2'
  - name: Telegram
    link: https://t.me/YunYouJun
    icon: ri:telegram-line
    color: '#0088CC'

avatar:
  enable: true
  url: /img/å¤´åƒ.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status: #çŠ¶æ€
    enable: false
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

# ç½‘ç«™é¦–é¡µ
# å‚ç›´äº¤é”™æ’åˆ—æ–‡å­—æ•ˆæœ
banner:
  enable: true
  title: æ¸´æœ›åšè‡ªå·±
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# å…¬å‘Š
notice:
  enable: false
  content: Thanks for playing my game.

bg_image:
  enable: true
  url: /img/å£çº¸.png
  # dark:
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

# å¡ç‰‡é€æ˜åº¦
post_card:
  opacity: 0.8

# å¡ç‰‡å†…ä¿¡æ¯
post_meta:
  item_text: false #æ˜¾ç¤ºæ–‡å­—
  created_at: true #åˆ›å»ºæ—¶é—´
  updated_at: true #æ›´æ–°æ—¶é—´
  categories: true #ç§ç±»
  tags: true #æ ‡ç­¾

# æ–‡ç« å†…
codeblock: # ä»£ç ä¸€é”®å¤åˆ¶
  copy_btn: true

creative_commons: #ç‰ˆæƒ
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false

# é¡µè„š
footer:
  since: 2022
  powered:
    enable: true
  custom_text: <a href="https://icp.gov.moe/?keyword=20228012" target="_blank">èŒICPå¤‡20228012å·</a>

# å¤‡æ³¨ï¼šä¸»é¢˜é…ç½®è§ https://yun.yunyoujun.cn/guide/config.html